### ISSUE TITLE
Please Enter a Valid Query. 

### ISSUE THREAD

**Issue by MiguelNiblock** [tmalch/lightningWeather#11]
Default location shown is Graz, AT. However, it doesn't allow me to type any other location, so I don't think it has to do with where I live. (I live in Los Angeles, CA so no issues with that) 

I've also messed with the C/F and the 3 providers, but still, it only gives me: "Please enter a valid query". 

Has this been solved before?

Linux Mint 19 Tessa
Thunderbird 60.2.1
Lightning Weather 0.4.0

**Comment by tmalch** [comment]
Yahoo changed/closed their API see #10 #9. No time at the moment will fix it possibly next week.
