### ISSUE TITLE
lightningWeather Options, Unit (Celcius/Farenheit) always reverts to Celcius

### ISSUE THREAD

**Issue by jim7734** [tmalch/lightningWeather#2]
Location: Cebu, PH Cebu
Provider: yahoo
Unit: Celcius

No matter which provider I choose, Whenever I set the unit to Farenheit and click OK, the unit reverts to Celcius.

![lightningweather bug](https://cloud.githubusercontent.com/assets/26043462/23341476/8a3e126c-fc83-11e6-9159-1039811bf7df.jpg)

**Comment by tmalch** [comment]
Hi and thanks for the report. I can reproduce this bug. Seems to be a problem with the initialisation of the gui, it doesn't read the selected unit but uses Celsius always.
The calender shows the temperature in the right unit anyway. 
I'll release a bugfix soon.

**Comment by bishopgodsey** [comment]
This still shows up as a bug in v0.2.1 with Thunderbird 52.1.0 on Windows 10. Tried elevating to admin and saving, still no joy. Reverts to C never does use F. 

Thanks!

**Comment by tmalch** [comment]
@bishopgodsey, 
Thanks for the good bug report, I was able to reproduce this on Windows. Seems the preference system of mozilla does not work as expected on Windows. Anyway workaround is on the way.
