### ISSUE TITLE
Do not work on Intranet entreprise

### ISSUE THREAD

**Issue by azimut2000** [tmalch/lightningWeather#5]
Hello !

I use this plugin on my personel computer and it work very well.... I wanted tu use it as well on my entreprise computer but we have a proxy on our network and it look to not be use by this module.

So, when on my enterprise computer, i can not find any town in order to initialyse this plugin and i have no access to weather.

**Comment by tmalch** [comment]
The plugin issues just simple http requests. All the network/proxy settings are handled by thunderbird. 
I have no experience with proxies but from my short research the problem might be that thunderbird is not configured to use the proxy for HTTP traffic, only for IMAP or whatever. Check Preferences->Advanced->Network & Disk Space ->Button "Settings..."
