### ISSUE TITLE
Does not work with Lightning 6.2 Thunderbird 60

### ISSUE THREAD

**Issue by hfball** [tmalch/lightningWeather#7]
Here's hoping you can update this extension to work with Thunderbird 60/Lightning 6.2. I find it to be really useful.

**Comment by tmalch** [comment]
Thanks for the report. 
If possible with reasonable effort I'll update it. Just have to find some time and motivation to investigate what's broken and how to fix it.

**Comment by dnfoo** [comment]
Is there something broken with Thunderbird 60/Lightning 6.2 indeed? Or is it just the metadata not claiming compatibility so it gets deactivated automatically?
Would be great to have it back!

**Comment by tmalch** [comment]
I uploaded a new version today that should be compatible with 60.*, hope it works. There were just some minor fixes necessary.

**Comment by hfball** [comment]
Is AMO sitting on the update? It still shows 0.3.2 on the add-ons site.

I tried downloading the source folders into an xpi to test it out, but that didn't work.

**Comment by tmalch** [comment]
Yes it seems their review process got quite slow recently. It is in queue position 12 now, it was 17 when I uploaded the new version 5 days ago. 
In the meantime you can also download v0.4.0 from github: [lightningweather.thomas.malcher.xpi](https://github.com/tmalch/lightningWeather/releases/download/v0.4.0/lightningweather.thomas.malcher.xpi) 
Use "Install Add-on From File..." feature to install it.
Also note that mozilla migrated all thunderbird addons to "addons.thunderbird.net/". So the new url for this is https://addons.thunderbird.net/thunderbird/addon/lightningweather/
