### ISSUE TITLE
More breakage updating from Tbird 60.3 to 60.4

### ISSUE THREAD

**Issue by hfball** [tmalch/lightningWeather#9]
Recently updated to Thunderbird 60.4.0 and LightningWeather broke again. It shows the past weather icons in the calendar, but appears to be unable to contact the weather services for new icons. I tried going into the configuration page and chose each weather service; each service shows "No Result" for the location when I type in my zip code or town. I concluded this means it has lost its connection to the services, as all three would not be out if it was simply an individual service outage.

I wish the folks at Mozilla would leave well enough alone and stop breaking stuff. Anyhow, good luck with it, if you decide it's still worth maintaining, and thank you.

**Comment by appoloin** [comment]
This isn't only weather extension/applet that broken in the last day.  Yahoo have change their API and WOEID is gone

**Comment by hfball** [comment]
Ugh. Well, best of luck with it. Thanks for writing a great extension, tmalch, whatever you decide to do with it.

**Comment by tmalch** [comment]
Thanks for the reports. Yes the problem is that Yahoo changed their API. They closed the geocoding API I used in the preferences and also their weather API.
Shouldn't be that hard to fix but this also has not very high priority for me. Because thunderbird is switching to WebExtensions, who knows how long it will support XUL extensions like this one.

**Comment by tmalch** [comment]
OK just pushed new release 0.5.0 available now on github and probably in some days through thunderbird addons.
Switched to HERE API for Geocoding and for the moment I removed the Yahoo weather API as weather data provider because it stopped working.
